### ISSUE TITLE
I cant write any symbols in 1.0 ver

### ISSUE THREAD

**Issue by Hufitgiyresfhii** [PrattaySarkar/BilepterOS#2]
So, when I press shift+any symbol it just cant print the symbols

also i will be working as a bug reporter

**Comment by PrattaySarkar** [comment]
Ik its outdated also only letters work

Ok u can be a bug repoter

**Comment by PrattaySarkar** [comment]
1.5 or 2.0?

**Comment by PrattaySarkar** [comment]
I think I cant fix 1.0 bc the osdev resources are outdated. You have to rely on 2.0 when it releases
